# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / Linux Shell
pages:
- Home: index.md
- Introduction: introduction.md
- Select and Install Shell Software: install.md
- User Environment Basics: user-env.md
- Shell Script Basics: shell-script-basics.md
- Shell Script Best Practices: best-practices.md
- Examples for Common Tasks: common-tasks.md
- Tips and Tricks: tips-and-tricks.md
- Troubleshooting: troubleshooting/troubleshooting.md
- Resources: resources.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
# Don't include the URL because don't really want direct editing on content and editor icons are irritating
# repo_url:  https://github.com/OpenWaterFoundation/owf-learn-linux-shell
site_description:  Open Water Foundation Learn Linux Shell
site_author:  Open Water Foundation
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  Copyright Open Water Foundation
# Extra options
# Use extra CSS to customize styles, based on theme
extra_css:
- 'css/extra-material-theme.css'
